#!/bin/bash

echo "Stop any running instaces"
docker-compose down

echo "Create docker network traefik"
docker network inspect traefik >/dev/null 2>&1 || docker network create --driver bridge traefik

echo "Starting traefik as a service"
docker-compose up -d

cat .env